# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: H10 Labs
:url: http://h10labs.com
:copyright: 2011
:analytics_code: UA-58268-4
