:headline: Explorations
:body:

:product:
  - 
    :name: Yum Video Search
    :turl: http://yum.heroku.com
    :desc: Search videos all over the web.
  -
    :name: Truveo Most Twittered Videos
    :turl: https://chrome.google.com/extensions/detail/ahidcamhgpefjpeaacopdlodlokphjdd?hl=en
    :desc: A Google Chrome Extension.
  -
    :name: Remove TechCrunch Comments
    :turl: https://chrome.google.com/extensions/detail/lnakacebcchaghkhjhakdjdddhclalgm?hl=en
    :desc: A Google Chrome Extension.
  -
    :name: Deli Sandwich
    :turl: http://deli.heroku.com
    :desc: A daily dish of delicious links, RSS included.

:comingsoon:
  - 
    :name: Bacon Bacon
    :desc: Who doesn't love bacon?
  - 
    :name: Muni Near Me
    :desc: Get me a bus, stat!
  - 
    :name: Radio Notifier
    :desc: What's on?
  - 
    :name: Hockey Goals
    :desc: Watch greatness.