:headline: Explorations
:body:

:product:
  - 
    :name: Yum Video Search
    :url:  http://yum.heroku.com
  - 
    :name: Bacon Bacon
  - 
    :name: Muni Near Me
  - 
    :name: Radio Notifier
  - 
    :name: Hockey Goals

  
